"""Daily runner: analyze all topics and send combined report via email."""

import json
import time
from datetime import date

import markdown

from graph import graph
from notifier import send_email

EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html>
<body style="margin:0; padding:0; background:#f4f4f4;">
<div style="max-width:700px; margin:20px auto; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; color:#333;">
  <div style="background:#1a1a2e; color:#fff; padding:30px; border-radius:12px 12px 0 0; text-align:center;">
    <h1 style="margin:0; font-size:24px;">Daily News Analysis Report</h1>
    <p style="margin:8px 0 0; opacity:0.8; font-size:14px;">{date}</p>
  </div>
  <div style="background:#fff; padding:10px 30px 30px; border-radius:0 0 12px 12px;">
    {sections}
  </div>
  <p style="text-align:center; font-size:12px; color:#999; margin-top:16px;">
    Generated by News Analyst Agent
  </p>
</div>
</body>
</html>"""

SECTION_TEMPLATE = """\
<div style="border:1px solid #e0e0e0; border-radius:8px; padding:20px; margin:20px 0; background:#fafafa;">
  <h2 style="margin:0 0 12px; color:#1a1a2e; font-size:20px; border-bottom:2px solid #e0e0e0; padding-bottom:8px;">{topic}</h2>
  <div style="line-height:1.7; font-size:14px;">{content}</div>
  <p style="margin:12px 0 0; font-size:12px; color:#999;">Completed in {elapsed:.1f}s</p>
</div>"""


def run_daily():
    with open("config.json") as f:
        config = json.load(f)

    topics = config["topics"]
    to_address = config["email"]["to"]
    today = date.today().isoformat()

    sections = []
    for topic in topics:
        print(f"Analyzing: {topic}")
        state = {
            "messages": [],
            "topic": topic,
            "news_items": [],
            "analysis": "",
            "conflicts": [],
            "iterations": 0,
            "final_report": "",
        }
        start = time.time()
        result = graph.invoke(state)
        elapsed = time.time() - start

        content_html = markdown.markdown(
            result["final_report"],
            extensions=["tables", "nl2br"],
        )
        sections.append(
            SECTION_TEMPLATE.format(topic=topic, content=content_html, elapsed=elapsed)
        )
        print(f"  Done in {elapsed:.1f}s")

    html_body = EMAIL_TEMPLATE.format(date=today, sections="\n".join(sections))
    subject = f"Daily News Report — {today}"

    send_email(subject, html_body, to_address)
    print(f"\nAll {len(topics)} topics analyzed and emailed.")


if __name__ == "__main__":
    run_daily()
