"""HTML email template for news reports."""

import re

import markdown

_HEADING_STYLES = {
    "h1": "font-size:18px; font-weight:700; color:#1a1a2e; margin:16px 0 6px;",
    "h2": "font-size:16px; font-weight:700; color:#1a1a2e; margin:14px 0 5px; border-bottom:1px solid #e0e0e0; padding-bottom:4px;",
    "h3": "font-size:14px; font-weight:600; color:#333; margin:12px 0 4px;",
}


def _style_headings(html: str) -> str:
    for tag, style in _HEADING_STYLES.items():
        html = re.sub(rf"<{tag}(\s[^>]*)?>", f'<{tag} style="{style}">', html)
    return html

EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html>
<body style="margin:0; padding:0; background:#f4f4f4;">
<div style="max-width:700px; margin:20px auto; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; color:#333;">
  <div style="background:#1a1a2e; color:#fff; padding:30px; border-radius:12px 12px 0 0; text-align:center;">
    <h1 style="margin:0; font-size:24px;">Daily News Analysis Report</h1>
    <p style="margin:8px 0 0; opacity:0.8; font-size:14px;">{date}</p>
  </div>
  <div style="background:#fff; padding:10px 30px 30px; border-radius:0 0 12px 12px;">
    {sections}
  </div>
  <p style="text-align:center; font-size:12px; color:#999; margin-top:16px;">
    Generated by News Analyst Agent | Model: {model}
  </p>
</div>
</body>
</html>"""

SECTION_TEMPLATE = """\
<div style="border:1px solid #e0e0e0; border-radius:8px; padding:20px; margin:20px 0; background:#fafafa;">
  <h2 style="margin:0 0 12px; color:#1a1a2e; font-size:20px; border-bottom:2px solid #e0e0e0; padding-bottom:8px;">📰 {topic}</h2>
  <div style="line-height:1.7; font-size:14px;">{content}</div>
  <p style="margin:12px 0 0; font-size:12px; color:#999;">Completed in {elapsed:.1f}s</p>
</div>"""


def build_report_html(today: str, reports: list[dict], model: str = "") -> str:
    """Build full HTML email from a list of topic reports.

    Each report dict should have: topic (str), final_report (str), elapsed (float).
    """
    sections = []
    for report in reports:
        content_html = _style_headings(markdown.markdown(
            report["final_report"],
            extensions=["tables", "nl2br"],
        ))
        sections.append(
            SECTION_TEMPLATE.format(
                topic=report["topic"],
                content=content_html,
                elapsed=report["elapsed"],
            )
        )
    return EMAIL_TEMPLATE.format(date=today, sections="\n".join(sections), model=model)
